/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n3.3.5-184-g64a16dfa87"
#endif /* AVUTIL_FFVERSION_H */
